//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

pub use super::districts::Entity as Districts;
pub use super::elections::Entity as Elections;
pub use super::super_districts::Entity as SuperDistricts;
