//! `SeaORM` Entity. Generated by sea-orm-codegen 0.10.6

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "super_districts")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub super_district_id: String,
    pub election_id: String,
    pub name: String,
    pub created_at: DateTimeUtc,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {
    #[sea_orm(has_many = "super::districts::Entity")]
    Districts,
    #[sea_orm(
        belongs_to = "super::elections::Entity",
        from = "Column::ElectionId",
        to = "super::elections::Column::ElectionId",
        on_update = "NoAction",
        on_delete = "Cascade"
    )]
    Elections,
}

impl Related<super::districts::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Districts.def()
    }
}

impl Related<super::elections::Entity> for Entity {
    fn to() -> RelationDef {
        Relation::Elections.def()
    }
}

impl ActiveModelBehavior for ActiveModel {}
